# Site wide configuration

title: JasonCarter.io
locale: en_US 
url:

# Jekyll configuration

permalink:   /:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner

owner:
  name: Jason Carter
  avatar: 
  bio: "Welcome to <strong>My Digital: {Home}</strong>. </br>A place for me to share with you my personal opinion on <strong>Digital Marketing</strong>, <strong>Analytics</strong> and <strong>Product Management</strong>."
  email: jason.ian.carter@gmail.com
  gravator_email_md5: 0afde15e66033cfc608c73a2b386a50d
  disqus-shortname: jasoncarter
  twitter: jasonicarter
  facebook: #username
  google:
    plus: #username
    analytics: UA-43596308-3
    verify: 
    ad-client: 
    ad-slot: 
  github: jasonicarter
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: jasoniancarter
  instagram: #username

# Group pages

groups:
  categories-path: categories
  tags-path: tags
  about-path: about
  more-path: more
  wordsplus-path: products/wordsplus
  portal-path: products/portal
  website-path: products/website

# Compilation stuff

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
